/** @format */

import type { Metadata } from "next";
import { Poppins, Montserrat, Pacifico } from "next/font/google";
import "./globals.css";
import { ImClubs } from "react-icons/im";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

const monsterrat = Montserrat({
	subsets: ["latin"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Casino",
	description: "Generated by create next app",
	icons:
		"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj6I14-3-nJPHqWSwLW-ERAldEOV6jpkGi6zPUfnlt3g&s",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.ico.png" sizes="any" />
			</head>
			<body className={`${poppins.className} ${monsterrat.className}`}>
				{children}
			</body>
		</html>
	);
}
